useTabs: false
endOfLine: lf
singleQuote: true
jsxSingleQuote: true
semi: false
singleAttributePerLine: true
quoteProps: 'as-needed'
bracketSpacing: false
printWidth: 120
overrides:
  - files: '*.json'
    options:
      printWidth: 70
  - files: '*.md'
    options:
      printWidth: 70
      useTabs: false
      trailingComma: none
      arrowParens: avoid
      proseWrap: never
