services:
  node:
    build: ./docker/node
    container_name: "taiki-karaoke"
    volumes:
      - ./node:/usr/src/app:cached
    command: sh -c "cd taiki-karaoke && yarn start"
    ports:
      - "3000:3000"
volumes:
  front-node-modules:
