services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: 'karaoke-front'
    volumes:
      - .:/home/node/karaoke:cached
      - node_modules:/home/node/karaoke/node_modules
    command: yarn start
    ports:
      - '3000:3000'
volumes:
  node_modules:

networks:
  default:
    external: true
    name: taiki-network
