services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile.prod
    container_name: "karaoke_front"
    environment:
      VIRTUAL_HOST: 'taiki-web.ninsan.mydns.jp'
    restart: always

networks:
  default:
    external: true
    name: taiki-network
