# ビルドフェーズ
FROM node:alpine
WORKDIR /karaoke
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

# 実行フェーズ
FROM nginx
COPY ./docker/nginx/conf.d/karaoke.conf /etc/nginx/conf.d/karaoke.conf
COPY --from=0 /karaoke/dist /usr/share/nginx/html/
